# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t2Ir_hsbtrouhaK44gFQd0ZDtRHraDfT
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
 
!git clone https://github.com/csinva/matching-with-gans.git

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x
import tensorflow as tf
import sys
import matplotlib.image as mpimage
import matplotlib.pyplot as plt
import os
from os.path import join
from PIL import Image
sys.path.append('matching-with-gans')
import util
from google.colab import files

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/matching-with-gans
!rm -rf upload
!mkdir -p upload
# %cd upload

temp = files.upload()
temp = list(temp.keys())
temp = temp[0]
 
img1_path = os.path.join("/content/matching-with-gans/upload", temp)
img1_filename = os.path.basename(img1_path)
img1_wo_ext = img1_filename.split(".")[0]
print("upload img1 file here:", img1_path)
 
temp = files.upload()
temp = list(temp.keys())
temp = temp[0]
 
img2_path = os.path.join("/content/matching-with-gans/upload", temp)
img2_filename = os.path.basename(img2_path)
img2_wo_ext = img2_filename.split(".")[0]
print("upload img2 file here:", img2_path)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/matching-with-gans
!rm -rf outputs
!mkdir -p outputs
# %cd outputs
!mkdir aligned projected manipulated

Raw_img_dir = '/content/matching-with-gans/upload'

Aligned_img_dir = '/content/matching-with-gans/outputs/aligned'
Plojected_img_dir = '/content/matching-with-gans/outputs/projected'
Manipulated_img_dir = '/content/matching-with-gans/outputs/manipulated'
Interpolated_img_dir = '/content/matching-with-gans/outputs/interpolated'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/matching-with-gans
 
!python ./projection_manipulation/scripts/00_align_images.py  {Raw_img_dir} {Aligned_img_dir}
 
im_raw = mpimage.imread(join(Raw_img_dir, img1_filename))
im_aligned = mpimage.imread(join(Aligned_img_dir, img1_wo_ext+"_01.jfif"))
util.plot_row([im_raw, im_aligned], annot_list=['original', 'aligned'])

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/matching-with-gans
 
!python ./projection_manipulation/scripts/01_project_images.py  {Aligned_img_dir} {Plojected_img_dir}
 
im_aligned = mpimage.imread(join(Aligned_img_dir, img1_wo_ext+"_01.jfif"))
im_projected = mpimage.imread(join(Aligned_img_dir, img1_wo_ext+"_01.jfif"))
util.plot_row([im_aligned, im_projected], annot_list=['aligned', 'projected'])

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/matching-with-gans
 
ATTRS_TO_ALTER = 'ACHG'
!python ./projection_manipulation/scripts/02_manipulate.py  {Plojected_img_dir} {Manipulated_img_dir} {ATTRS_TO_ALTER}
 
Image.open(join(Manipulated_img_dir, img1_wo_ext+"_01.jfif"))

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/matching-with-gans
 
!python ./projection_manipulation/scripts/02_interpolate.py  {Plojected_img_dir} {Interpolated_img_dir}
 
Image.open(join(Interpolated_img_dir, img2_wo_ext + "_01_" + img1_wo_ext +"_01.png"))